OPENAI_API_KEY = "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"
HUGGINGFACEHUB_API_TOKEN = "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"

# Email Configuration (for Gmail)
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "vkhiremath18@gmail.com"
SENDER_PASSWORD = "xyoq tjuc artk gfhe"  # Use App Password, not regular password