OPENAI_API_KEY = key
HUGGINGFACEHUB_API_TOKEN = key

# Email Configuration (for Gmail)
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = mail
SENDER_PASSWORD = password  # Use App Password, not regular password
